"""simplify_credit_card_limits

Revision ID: 0376f54c32e2
Revises: 76fc809fdfdc
Create Date: 2026-03-02 12:21:15.849848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0376f54c32e2'
down_revision: Union[str, None] = '76fc809fdfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_products', 'shared_limit')
    op.drop_column('financial_products', 'limit_single_payment')
    op.drop_column('financial_products', 'unified_limit')
    op.drop_column('financial_products', 'limit_installments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_products', sa.Column('limit_installments', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('financial_products', sa.Column('unified_limit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('financial_products', sa.Column('limit_single_payment', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('financial_products', sa.Column('shared_limit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
