"""Add shared_credit_limit to FinancialInstitution

Revision ID: 06a45999a9b5
Revises: f04ee65b7481
Create Date: 2026-03-03 19:58:22.526555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a45999a9b5'
down_revision: Union[str, None] = 'f04ee65b7481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_fsm_states')
    op.add_column('financial_institutions', sa.Column('has_shared_credit_limit', sa.Boolean(), nullable=True))
    op.add_column('financial_institutions', sa.Column('shared_credit_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    
    # Backfill: set NULL booleans to False for existing rows
    op.execute("UPDATE financial_institutions SET has_shared_credit_limit = FALSE WHERE has_shared_credit_limit IS NULL")
    op.execute("UPDATE financial_institutions SET share_summary = FALSE WHERE share_summary IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_institutions', 'shared_credit_limit')
    op.drop_column('financial_institutions', 'has_shared_credit_limit')
    op.create_table('telegram_fsm_states',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='telegram_fsm_states_pkey')
    )
    # ### end Alembic commands ###
