"""add_auto_debit_to_services

Revision ID: 50a27597ba24
Revises: f94307e35e0d
Create Date: 2026-03-02 18:53:50.966020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a27597ba24'
down_revision: Union[str, None] = 'f94307e35e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('services', sa.Column('auto_debit', sa.Boolean(), nullable=True))
    op.execute("UPDATE services SET auto_debit = false WHERE auto_debit IS NULL")
    op.alter_column('services', 'auto_debit', nullable=False, server_default='false')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'auto_debit')
    # ### end Alembic commands ###
