"""verify_models_sync

Revision ID: 76fc809fdfdc
Revises: 
Create Date: 2026-02-10 18:52:53.535650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fc809fdfdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
