"""set_null_on_delete_service_bill_fk

Revision ID: f04ee65b7481
Revises: 50a27597ba24
Create Date: 2026-03-03 12:02:45.690741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04ee65b7481'
down_revision: Union[str, None] = '50a27597ba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'auto_debit',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('transactions_service_bill_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'service_bills', ['service_bill_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_service_bill_id_fkey', 'transactions', 'service_bills', ['service_bill_id'], ['id'])
    op.alter_column('services', 'auto_debit',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
