"""add_currency_to_service_bills

Revision ID: f94307e35e0d
Revises: 0376f54c32e2
Create Date: 2026-03-02 18:28:09.405745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94307e35e0d'
down_revision: Union[str, None] = '0376f54c32e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add as nullable first, backfill existing rows, then set NOT NULL
    op.add_column('service_bills', sa.Column('currency', sa.String(length=10), nullable=True))
    op.execute("UPDATE service_bills SET currency = 'ARS' WHERE currency IS NULL")
    op.alter_column('service_bills', 'currency', nullable=False, server_default='ARS')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_bills', 'currency')
    # ### end Alembic commands ###
